<?php

$lang['home'] = 'Home';
// style.ini values
$lang['__background_site__'] = 'Color for the very background (behind the content box)';
$lang['__link__']            = 'The general link color';
$lang['__existing__']        = 'The color for links to existing pages';
$lang['__missing__']         = 'The color for links to non-existing pages';
$lang['__site_width__']      = 'The width of the full site (can be any length unit: %, px, em, ...)';
$lang['__sidebar_width__']   = 'The width of the sidebar, if any (can be any length unit: %, px, em, ...)';
$lang['__tablet_width__']    = 'Below screensizes of this width, the site switches to tablet mode';
$lang['__phone_width__']     = 'Below screensizes of this width, the site switches to phone mode';
$lang['__theme_color__']     = 'Theme color of the web app';

$lang['__logo_color__']           = 'Logo color';
$lang['__logo_font__']            = 'Logo font family';
$lang['__outer_background__']     = 'Color for the full page background (outside of reading panel)';
$lang['__topbar_bg__']            = 'Color for the background in top bar';
$lang['__topbar_text__']          = 'Color for the text links in the top bar';
$lang['__topbar_topicbg__']       = 'Color for the background in the inner Topics panel';
$lang['__topbar_topictxt__']      = 'Color for the text in the inner Topics panel';

$lang['__lists_color__']          = 'Color for the text in the autogenerated lists';
$lang['__bullet_lists_color__']   = 'Color for bullets in the autogenerated lists';
$lang['__lists_weight__']         = 'Font weight in autogenerated lists';
$lang['__lists_background__']     = 'Color for the background in autogenerated lists';
$lang['__lists_font__']           = 'Font family to use in autogenerated lists';

$lang['__custom_link_topics__']   = 'Text color for the Custom Link in the inner Topics panel';

//$lang['menu'] = 'Navigator Labels';



